### ISSUE TITLE
Add PandasDatasetLoader

### ISSUE THREAD

**Issue by djvergel** [microsoft/causica#14]
Would it be possible to add `PandasDatasetLoader` (https://github.com/microsoft/project-azua/blob/main/azua/datasets/pandas_dataset_loader.py) to this project? It should be almost a straight copy since the `CSVDatasetLoader` looks the same in both projects.

**Comment by agrinh** [comment]
Thanks for raising this issue. We will be releasing a major revision which will include functionality to load dataframes and CSVs using standard PyTorch Datasets.
