### ISSUE TITLE
DECI Examples

### ISSUE THREAD

**Issue by moshe-salhov** [microsoft/causica#21]
Hello,
Really amazing work!!.
Small issue - is it possible to fix the notebooks under the DECI examples so it will be possible to run them?
Currently there are several issues that prevent such run:
1. metrics_logger not defined under the run_context
2. model run_train doesnt accept run_context=run_context
3. mode_f_sem is not supported under model_config when running DECI()
4. RunContext has no attribute get (I suspect that since "evaluation_pipline.aml_run_context" is not available there is a mismatch in RunContext functionality )

Many thanks

**Comment by mry-tvk** [comment]
Adding another point to this:
5- since the name of the repo is causica maybe the imports should be changed as below:
"from open_source.causica.models.deci.deci import DECI" -->"from causica.causica.models.deci.deci import DECI"

**Comment by confoundry** [comment]
Closing as the file no longer exists
