### ISSUE TITLE
Relative imports

### ISSUE THREAD

**Issue by DanielLSM** [microsoft/causica#24]
I'm not sure of the choice to have a sea of relative imports, but just trying to run out of the box: https://github.com/microsoft/causica/blob/9826ee9ba7dd63d72aaa0b3e0fd09636e38dd5bc/README.md?plain=1#L55
You get an 'ImportError: attempted relative import with no known parent package'

I get similar errors while trying to generate data: https://github.com/microsoft/causica/blob/9826ee9ba7dd63d72aaa0b3e0fd09636e38dd5bc/README.md?plain=1#L71

How does this run out of the box? Thanks

**Comment by akdadewrwr** [comment]
I face the same problem. Here is my solution.

Put `run_experiment.py` file on the root directory (before is `/causica/causica/run_experiment.py`, move the file out of inner `causica` folder ) and run
`python run_experiment.py csuite_symprod_simpson --model_type deci_spline --model_config configs/deci/true_graph_deci_spline.json -dc configs/dataset_config_causal_dataset.json -c -te`

**Comment by confoundry** [comment]
From the root directory you should be able to run:

```python -m causica.data_generation.csuite.simulate```

to generate the data. Then:

`python -m causica.run_experiment csuite_symprod_simpson --model_type deci_spline --model_config configs/deci/true_graph_deci_spline.json -dc configs/dataset_config_causal_dataset.json -c -te`

I'll update the README to reflect this. The sea of relative imports will be going away soon as we're releasing a major change soon.

**Comment by confoundry** [comment]
Closing now as the new version has been released
