### ISSUE TITLE
Accessing generated causal graph(s)

### ISSUE THREAD

**Issue by hesham-nawaz** [microsoft/causica#35]
Hi,

I was wondering what's the best way to obtain the learnt causal graphs after training DECI on my dataset. I know there are models stored in best_model.pt and last_model.pt but I'm not sure how to get the causal graphs from there (for the purpose of visualization). Happy to explain further if the question isn't clear and thanks for the great library!

**Comment by confoundry** [comment]
Hi,

You will need to access the variational distribution over graphs. You can either sample from that distribution, or get the mode (or the mean but that's not in the sample space). If training has worked, the distribution will probably be fairly tightly unimodal so the mode and the samples will be pretty similar.

`eval_csuite_example.py` gives a demo of how to load up a model file after training and evaluate it. It samples graphs and evaluates the samples against the true adjacency matrix. Hope that helps!
