### ISSUE TITLE
Command errored out with exit status 128.

### ISSUE THREAD

**Issue by ramicetty** [microsoft/causica#4]
https://github.com/microsoft/causica/blob/a3cfb90aa2bd61b1807dcfbf4f44b756ad7b31bd/environment.yml#L48
<img width="1728" alt="Screenshot 2022-07-02 at 10 45 13" src="https://user-images.githubusercontent.com/11596458/176989011-656fde34-24d2-4b5a-9ffe-c1f813b78d19.png">

**Comment by confoundry** [comment]
Hi @ramicetty, I've changed the build system to poetry, so I will close this issue. If you still have problems, please open another one!
