### ISSUE TITLE
The example - Multi-investment Sales Attribution is not working

### ISSUE THREAD

**Issue by ckayay** [microsoft/causica#40]
The Multi-investment Sales Attribution Notebook under examples / causal_ai_suite is giving error at line 152 when trying to run the ate function.

![image](https://user-images.githubusercontent.com/12582721/230304787-c02cf8e7-6d63-4e94-a107-9623f902a5b4.png)

![image](https://user-images.githubusercontent.com/12582721/230305271-bd690193-04f7-444b-b5c5-a8595ebd8cb1.png)

**Comment by confoundry** [comment]
Hi @ckayay,

I've updated the notebook to run with the newer code, hopefully that should work.

Thanks
