### ISSUE TITLE
Version mismatch? example codes not working

### ISSUE THREAD

**Issue by sujoyrc** [microsoft/causica#48]
When I pip install causica it installs correctly but then have various issues with both the sample codes.

for the csuite_example.ipynb when I run the first cell I get

`
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 10
      7 from tensordict import TensorDict
      8 from torch.utils.data import DataLoader
---> 10 from causica.datasets.causica_dataset_format import DataEnum, load_data
     11 from causica.datasets.tensordict_utils import tensordict_shapes
     12 from causica.distributions import (
     13     AdjacencyDistribution,
     14     ContinuousNoiseDist,
   (...)
     20     create_noise_modules,
     21 )

ModuleNotFoundError: No module named 'causica.datasets.causica_dataset_format'
`

Similarly when I run the multi_investment_sales_attribute.ipynb I get

`
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 18
     15 from pytorch_lightning.callbacks import TQDMProgressBar
     16 from tensordict import TensorDict
---> 18 from causica.distributions import (
     19     ContinuousNoiseDist,
     20     SEMDistributionModule,
     21 )
     22 from causica.lightning.data_modules.basic_data_module import BasicDECIDataModule
     23 from causica.lightning.modules.deci_module import DECIModule

ImportError: cannot import name 'ContinuousNoiseDist' from 'causica.distributions' (/opt/homebrew/lib/python3.8/site-packages/causica/distributions/__init__.py)
`

Please suggest changes ?

**Comment by confoundry** [comment]
Hi @sujoyrc 

Given that it's the first causica import that fails in both cases, and those paths do exist, I don't think it's the notebooks. The python importer might be trying to import a local module depending on where you are running it from. Try running python in a terminal and doing the imports manually from different locations.

**Comment by sujoyrc** [comment]
```
>>> import causica
>>> from causica import datasets
>>> from causica.datasets import causica_dataset_format
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'causica_dataset_format' from 'causica.datasets' (/opt/homebrew/lib/python3.8/site-packages/causica/datasets/__init__.py)
```

running from a different prompt in a different directory

```
>>> import causica
>>> from causica import distributions
>>> from causica.distributions import ContinuousNoiseDist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ContinuousNoiseDist' from 'causica.distributions' (/opt/homebrew/lib/python3.8/site-packages/causica/distributions/__init__.py)
```

on a different directory

```
>>> import causica
>>> from causica import distributions
>>> from causica.distributions import *
>>> SEMDistribution()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'SEMDistribution' is not defined
```

Again on a different directory - some things on causica.distributions work but others dont !!!

```
>>> from causica.distributions import adjacency
>>> from causica.distributions.adjacency import AdjacencyDistribution
>>> from causica.distributions import SEMDistributionModule
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'SEMDistributionModule' from 'causica.distributions' (/opt/homebrew/lib/python3.8/site-packages/causica/distributions/__init__.py)
>>> from causica.distributions import ContinuousNoiseDist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ContinuousNoiseDist' from 'causica.distributions' (/opt/homebrew/lib/python3.8/site-packages/causica/distributions/__init__.py)
```

Please advice

**Comment by confoundry** [comment]
Thanks for the response. There is a circular import which is causing the problem. I will push the fix on Monday

**Comment by confoundry** [comment]
Hi,
I've pushed the new release to PyPI, please let me know if it works now!

**Comment by sujoyrc** [comment]
Thank you and sorry for the late response - was very busy to pull this and try. So this is working on a unix environment and also on google colab but having the same issue with my Mac. Any suggestions / are you aware of any Macbook Pro M1 (no GPU) challenges ?
