### ISSUE TITLE
Putting back the initial high-level DECI API

### ISSUE THREAD

**Issue by jdjelic** [microsoft/causica#50]
Dear Causica Dev Team, 

When can the re-introduction of the original (v0.0.0) high-level DECI API be expected? 
The recent low-level API makes it much harder to start a project and more difficult to tune up everything manually.
I loved the high-level API, especially the part for generating counterfactual estimates. I don't know how to calculate counterfactuals with the low-level API (existing tutorials do not cover it, as far as I saw).
Thank you!

**Comment by confoundry** [comment]
Hi @jdjelic 

There are no plans to revert to the previous DECI API, as we've moved over to use PyTorch Lightning for training and evaluation. The documentation is a little sparse at the minute so we will add a counterfactual example to the sales attribution notebook. 

If you want to get started with counterfactuals, check out the high-level function `counterfactual` in `sem/structural_equation_model.py`

Thanks

**Comment by jdjelic** [comment]
Thanks a lot for your response and recommendation!
