### ISSUE TITLE
Impossible to download the data in example multi_investment_sales_attribution.ipynb

### ISSUE THREAD

**Issue by fred887** [microsoft/causica#53]
Hi,

Inside the notebook example **multi_investment_sales_attribution.ipynb** I have an error when I try to download the data:

The command:

```python
root_path = "https://azuastoragepublic.blob.core.windows.net/datasets/causal_ai_suite"
df = pd.read_csv(root_path + "/multi_attribution_data_20220819.csv")
```

The error message:
>   642 def http_error_default(self, req, fp, code, msg, hdrs):
>--> 643     raise HTTPError(req.full_url, code, msg, hdrs, fp)
>
>HTTPError: HTTP Error 409: Public access is not permitted on this storage account.

It seems that there is an issue with the data server. Has the address of the data changed?

Thanks a lot for your help

**Comment by confoundry** [comment]
Hi @fred887,

Thanks for the message. Direct public access to the blob storage has been revoked by the Microsoft security team. I have a PR for the fix (https://github.com/microsoft/causica/pull/54) which should get merged on Monday.

For now, if you change `root_path` to `root_path = "https://azuastoragepublic.z6.web.core.windows.net/causal_ai_suite"` that should work

**Comment by confoundry** [comment]
Hi @fred887 

I've pushed the changes to the main branch as well as PyPI, so hopefully this issue is resolved now! Thanks for bringing it up

**Comment by fred887** [comment]
That's working, thanks a lot!
