### ISSUE TITLE
Adding News, IHDP and TGCA datasets?

### ISSUE THREAD

**Issue by priamai** [microsoft/causica#55]
Hi there,
starting my journey with CAUSICA, any plans to add examples with this other 3 datasets?
https://github.com/d909b/perfect_match/tree/master
Cheers.

**Comment by confoundry** [comment]
In the DECI paper (https://arxiv.org/pdf/2202.02195.pdf), we used Twins and IHDP. We haven't got around to putting these into the refactored codebase, but should do. We don't have any plans to add the others. If you implement them, feel free to submit a PR!
