### ISSUE TITLE
Run with my own dataset

### ISSUE THREAD

**Issue by peterzhb** [microsoft/causica#6]
Hi,

I'm wondering if there is a guide on how to run experiment with my own dataset?

Thank you so much.

**Comment by pallavi787** [comment]
@peterzhb  Hope this example may help you. https://github.com/microsoft/causica/tree/main/examples/neurips_competition/starting_kit/task_1

**Comment by ramicetty** [comment]
@peterzhb Hope this example may help you. https://github.com/microsoft/causica/tree/main/examples/neurips_competition/starting_kit/task_1

**Comment by peterzhb** [comment]
I may have asked for too much. But my point was that it would be better if I could simply have a .csv file and the program can run and an interface to inject the causal graph. :)

**Comment by confoundry** [comment]
Hi @peterzhb, we're working on making an interface more like you described, but it will be a couple of months before it's ready.

**Comment by mry-tvk** [comment]
Hi @peterzhb, would you mind checking [this repo](https://github.com/mry-tvk/causica-examples) and see if it is useful for your ask? Just looking to get feedback. Thanks
